version: 2.1

restore_cache: &restore_cache
  - run:
    name: Restore Yarn Package Cache
    keys:
      - yarn-packages-{{ checksum "yarn.lock" }}

jobs:
  run_tests:
    docker:
      - image: 'cimg/node:14.14.0'
    steps:
      - checkout
      - *restore_cache
      - install:
          name: Install Dependencies
          command: yarn install --immutable
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - test: yarn run test
      - run: node --version

workflows:
  node-tests:
    jobs:
      - run_tests
