version: 2.1
orbs:
  node: circleci/node@3.0.0

jobs:
  build:
    docker:
      - image: 'cimg/node:14.14.0'
    steps:
      - run: node --version


workflows:
  node-tests:
    jobs:
      - build
      - node/test
